import { readFileSync, writeFileSync } from "node:fs";
// Reviewed source translations. Order: English, Chinese, German, Spanish, Russian, Italian, Japanese.
const rows = `Non renseigné|Not specified|未填写|Nicht angegeben|Sin especificar|Не указано|Non specificato|未入力
Sensor Studio · Revue de conception|Sensor Studio · Design review|Sensor Studio · 设计评审|Sensor Studio · Designprüfung|Sensor Studio · Revisión de diseño|Sensor Studio · Проверка проекта|Sensor Studio · Revisione del progetto|Sensor Studio · 設計レビュー
Du montage à une décision documentée|From assembly to a documented decision|从装配到有据可查的决策|Vom Aufbau zur dokumentierten Entscheidung|Del montaje a una decisión documentada|От сборки к обоснованному решению|Dal montaggio a una decisione documentata|組立から根拠のある判断へ
Comparez vos entrefers aux données publiées, puis préparez les essais qui manquent.|Compare your gaps with published data, then prepare the missing tests.|将间隙与公布数据比较，然后准备缺失的测试。|Vergleichen Sie Ihre Abstände mit veröffentlichten Daten und planen Sie fehlende Tests.|Compare las separaciones con los datos publicados y prepare los ensayos pendientes.|Сравните зазоры с опубликованными данными и подготовьте недостающие испытания.|Confrontate i traferri con i dati pubblicati e preparate le prove mancanti.|ギャップを公開データと比較し、不足する試験を準備します。
Réinitialiser la démonstration|Reset demo|重置演示|Demo zurücksetzen|Reiniciar demostración|Сбросить демонстрацию|Reimposta demo|デモをリセット
Démonstration guidée|Guided demo|引导演示|Geführte Demo|Demostración guiada|Пошаговая демонстрация|Demo guidata|ガイド付きデモ
Données d'exemple|Example data|示例数据|Beispieldaten|Datos de ejemplo|Примерные данные|Dati di esempio|サンプルデータ
1. Jouez le cycle. 2. Comparez les écarts. 3. Changez la tolérance. 4. Confirmez les hypothèses. 5. Exportez la fiche.|1. Play the cycle. 2. Compare margins. 3. Change tolerance. 4. Confirm assumptions. 5. Export the review.|1. 播放循环。2. 比较裕量。3. 修改公差。4. 确认假设。5. 导出评审。|1. Zyklus starten. 2. Abstände vergleichen. 3. Toleranz ändern. 4. Annahmen bestätigen. 5. Bericht exportieren.|1. Ejecute el ciclo. 2. Compare márgenes. 3. Cambie la tolerancia. 4. Confirme hipótesis. 5. Exporte la ficha.|1. Запустите цикл. 2. Сравните запасы. 3. Измените допуск. 4. Подтвердите гипотезы. 5. Экспортируйте отчёт.|1. Avviate il ciclo. 2. Confrontate i margini. 3. Cambiate la tolleranza. 4. Confermate le ipotesi. 5. Esportate la scheda.|1. サイクルを再生。2. 余裕を比較。3. 公差を変更。4. 仮定を確認。5. レビューを出力。
{0} famille(s) documentée(s) sur {1}|{0} documented families out of {1}|共 {1} 个系列，{0} 个有文档|{0} dokumentierte Familien von {1}|{0} familias documentadas de {1}|Документировано семейств: {0} из {1}|{0} famiglie documentate su {1}|{1} 系列中 {0} 系列に公開データあり
{0} famille(s) physiquement calibrée(s) sur {1}|{0} physically calibrated families out of {1}|共 {1} 个系列，{0} 个完成物理标定|{0} physikalisch kalibrierte Familien von {1}|{0} familias calibradas físicamente de {1}|Физически откалибровано семейств: {0} из {1}|{0} famiglie calibrate fisicamente su {1}|{1} 系列中 {0} 系列を物理校正済み
4 classes de sensibilité ne sont pas 4 capteurs|4 sensitivity classes are not 4 sensors|4 个灵敏度等级不等于 4 个传感器|4 Empfindlichkeitsklassen sind keine 4 Sensoren|4 clases de sensibilidad no son 4 sensores|4 класса чувствительности — не 4 датчика|4 classi di sensibilità non sono 4 sensori|感度4クラスはセンサー4種類ではありません
Les distances publiées sont typiques. Les écarts affichés ne garantissent ni le pire cas, ni le comportement en température, ni une pose différente.|Published distances are typical. Displayed margins do not guarantee worst-case performance, temperature behaviour or a different pose.|公布距离为典型值。显示裕量不保证最坏情况、温度影响或不同姿态下的性能。|Veröffentlichte Abstände sind typische Werte. Die Abstände garantieren weder den ungünstigsten Fall noch Temperaturverhalten oder andere Posen.|Las distancias publicadas son típicas. Los márgenes no garantizan el peor caso, el comportamiento térmico ni otra posición.|Опубликованы типовые расстояния. Запасы не гарантируют худший случай, поведение при температуре или иной позиции.|Le distanze pubblicate sono tipiche. I margini non garantiscono il caso peggiore, il comportamento termico o una posa diversa.|公開距離は代表値です。表示する余裕は最悪条件、温度特性、別の配置での動作を保証しません。
Saisie invalide : vérifiez les valeurs et leur ordre.|Invalid input: check values and their order.|输入无效：请检查数值及顺序。|Ungültige Eingabe: Werte und Reihenfolge prüfen.|Entrada inválida: compruebe valores y orden.|Некорректный ввод: проверьте значения и порядок.|Dati non validi: controllate valori e ordine.|入力が無効です。値と順序を確認してください。
Espace des solutions|Solution space|方案空间|Lösungsraum|Espacio de soluciones|Пространство решений|Spazio delle soluzioni|解の比較
Tri par écart de fermeture décroissant, sans recommandation automatique.|Sorted by decreasing closing margin; no automatic recommendation.|按闭合裕量降序排列，不自动推荐。|Nach abnehmendem Schließabstand sortiert, ohne automatische Empfehlung.|Orden por margen de cierre descendente, sin recomendación automática.|Сортировка по убыванию запаса замыкания, без автоматической рекомендации.|Ordine per margine di chiusura decrescente, senza raccomandazione automatica.|閉成余裕の降順です。自動推奨ではありません。
Trier|Sort|排序|Sortieren|Ordenar|Сортировать|Ordina|並べ替え
Écart de fermeture|Closing margin|闭合裕量|Schließreserve|Margen de cierre|Запас замыкания|Margine di chiusura|閉成余裕
Écart d'ouverture|Opening margin|断开裕量|Öffnungsreserve|Margen de apertura|Запас размыкания|Margine di apertura|開離余裕
Comparaison aux valeurs typiques|Comparison with typical values|与典型值比较|Vergleich mit typischen Werten|Comparación con valores típicos|Сравнение с типовыми значениями|Confronto con valori tipici|代表値との比較
Voir les bandes d'entrefer|Show gap bands|显示间隙区间|Abstandsbänder anzeigen|Ver bandas de separación|Показать полосы зазоров|Mostra bande dei traferri|ギャップ帯を表示
Bandes des distances typiques et entrefers déclarés|Typical distance bands and declared gaps|典型距离区间与声明间隙|Typische Abstandsbänder und angegebene Abstände|Bandas típicas y separaciones declaradas|Типовые полосы расстояний и заявленные зазоры|Bande tipiche e traferri dichiarati|代表距離帯と入力ギャップ
Trait plein : fermeture avec tolérance. Pointillés : ouverture avec tolérance. Bande : hystérésis typique.|Solid line: closure with tolerance. Dashed: opening with tolerance. Band: typical hysteresis.|实线：含公差闭合。虚线：含公差断开。区间：典型迟滞。|Durchgezogen: Schließen mit Toleranz. Gestrichelt: Öffnen mit Toleranz. Band: typische Hysterese.|Línea continua: cierre con tolerancia. Discontinua: apertura con tolerancia. Banda: histéresis típica.|Сплошная: замыкание с допуском. Пунктир: размыкание с допуском. Полоса: типовой гистерезис.|Linea continua: chiusura con tolleranza. Tratteggio: apertura con tolleranza. Banda: isteresi tipica.|実線：公差を含む閉成。破線：公差を含む開離。帯：代表ヒステリシス。
Données manquantes pour la prédiction physique : géométrie active, repères et validation indépendante.|Missing for physical prediction: active geometry, datums and independent validation.|物理预测缺少：有效几何、基准及独立验证。|Für die physikalische Vorhersage fehlen aktive Geometrie, Bezugspunkte und unabhängige Validierung.|Faltan geometría activa, referencias y validación independiente para la predicción física.|Для физического прогноза не хватает активной геометрии, баз и независимой проверки.|Per la previsione fisica mancano geometria attiva, riferimenti e validazione indipendente.|物理予測には有効形状、基準、独立検証が不足しています。
Contributions inconnues|Unknown contributions|未知因素|Unbekannte Beiträge|Contribuciones desconocidas|Неизвестные составляющие|Contributi sconosciuti|不明な寄与
Où votre conception casse|Where your design fails|设计失效边界|Wo Ihr Entwurf versagt|Dónde falla el diseño|Где проект перестаёт работать|Dove il progetto non regge|設計が成立しなくなる条件
Appliquer au montage|Apply to assembly|应用到装配|Auf Aufbau anwenden|Aplicar al montaje|Применить к сборке|Applica al montaggio|配置に適用
Sélectionnez une ligne pour examiner ses sources et ses limites.|Select a row to inspect sources and limits.|选择一行查看来源和限制。|Zeile auswählen, um Quellen und Grenzen zu prüfen.|Seleccione una fila para examinar fuentes y límites.|Выберите строку для просмотра источников и ограничений.|Selezionate una riga per esaminare fonti e limiti.|行を選択して出典と制約を確認します。
Dossier : hypothèses à confirmer|Dossier: assumptions to confirm|项目：待确认假设|Dossier: Annahmen bestätigen|Expediente: hipótesis por confirmar|Досье: гипотезы для подтверждения|Dossier: ipotesi da confermare|案件：確認が必要な仮定
confirmés|confirmed|已确认|bestätigt|confirmados|подтверждено|confermati|確認済み
Une proposition de l'atelier reste une hypothèse jusqu'à votre confirmation. Les valeurs confirmées sont conservées lors d'un changement de montage.|Workshop proposals remain assumptions until confirmed. Confirmed values survive assembly changes.|工作区建议在您确认前仍是假设。更改装配时保留已确认值。|Werkstattvorschläge bleiben bis zur Bestätigung Annahmen. Bestätigte Werte bleiben bei Aufbauänderungen erhalten.|Las propuestas siguen siendo hipótesis hasta confirmarlas. Los valores confirmados se conservan al cambiar el montaje.|Предложения остаются гипотезами до подтверждения. Подтверждённые значения сохраняются при изменении сборки.|Le proposte restano ipotesi fino alla conferma. I valori confermati restano dopo modifiche al montaggio.|提案は確認するまで仮定です。確認済みの値は配置変更後も保持されます。
Source : atelier|Source: workshop|来源：工作区|Quelle: Werkstatt|Fuente: taller|Источник: мастерская|Fonte: laboratorio|出典：ワークショップ
Source : utilisateur|Source: user|来源：用户|Quelle: Benutzer|Fuente: usuario|Источник: пользователь|Fonte: utente|出典：ユーザー
Confirmer|Confirm|确认|Bestätigen|Confirmar|Подтвердить|Conferma|確認
Le montage propose une autre valeur|Assembly suggests another value|装配建议另一个值|Aufbau schlägt einen anderen Wert vor|El montaje propone otro valor|Сборка предлагает другое значение|Il montaggio propone un altro valore|配置から別の値が提案されています
Utiliser cette hypothèse|Use this assumption|使用此假设|Diese Annahme verwenden|Usar esta hipótesis|Использовать эту гипотезу|Usa questa ipotesi|この仮定を使用
Données à demander à Standex|Data to request from Standex|需向 Standex 索取的数据|Bei Standex anzufordernde Daten|Datos que solicitar a Standex|Данные для запроса у Standex|Dati da richiedere a Standex|Standexに依頼するデータ
Chaque donnée demandée lève une limite identifiée. Les demandes A à D sont prioritaires pour la calibration.|Each requested item addresses a known limitation. Requests A to D have calibration priority.|每项数据都对应已知限制。标定优先需要 A 至 D。|Jede Angabe beseitigt eine bekannte Grenze. A bis D haben für die Kalibrierung Vorrang.|Cada dato resuelve una limitación conocida. A a D son prioritarios para calibrar.|Каждый пункт устраняет известное ограничение. Для калибровки приоритетны A–D.|Ogni dato risolve un limite noto. Le richieste A–D hanno priorità per la calibrazione.|各データは既知の制約に対応します。校正ではA～Dを優先します。
Exporter la liste|Export list|导出列表|Liste exportieren|Exportar lista|Экспорт списка|Esporta elenco|一覧を出力
Générer la fiche de revue|Generate review sheet|生成评审表|Prüfblatt erstellen|Generar ficha de revisión|Создать лист проверки|Genera scheda di revisione|レビュー票を作成
Vérifier une empreinte JSON|Verify a JSON fingerprint|验证 JSON 指纹|JSON-Fingerabdruck prüfen|Verificar huella JSON|Проверить отпечаток JSON|Verifica impronta JSON|JSONフィンガープリントを検証
Non contre-signée|Not countersigned|未会签|Nicht gegengezeichnet|Sin contrafirma|Без контрподписи|Non controfirmata|副署なし
Fiche de revue de conception|Design review sheet|设计评审表|Designprüfblatt|Ficha de revisión de diseño|Лист проверки проекта|Scheda di revisione del progetto|設計レビュー票
Une modification du montage ou des déclarations impose une nouvelle fiche.|Changing assembly or declarations requires a new sheet.|修改装配或声明后需重新生成评审表。|Änderungen am Aufbau oder an Angaben erfordern ein neues Blatt.|Modificar el montaje o las declaraciones requiere una nueva ficha.|Изменение сборки или заявлений требует нового листа.|Modificare montaggio o dichiarazioni richiede una nuova scheda.|配置や入力を変更した場合、新しい票が必要です。
Exporter JSON|Export JSON|导出 JSON|JSON exportieren|Exportar JSON|Экспорт JSON|Esporta JSON|JSON出力
Exporter Markdown|Export Markdown|导出 Markdown|Markdown exportieren|Exportar Markdown|Экспорт Markdown|Esporta Markdown|Markdown出力
Imprimer|Print|打印|Drucken|Imprimir|Печать|Stampa|印刷
Ce qui est détecté|What is detected|检测对象|Was erkannt wird|Qué se detecta|Что обнаруживается|Cosa viene rilevato|検出対象
Le montage|The assembly|装配|Der Aufbau|El montaje|Сборка|Il montaggio|配置
Le résultat|The result|结果|Das Ergebnis|El resultado|Результат|Il risultato|結果
Les hypothèses retenues|Retained assumptions|采用的假设|Verwendete Annahmen|Hipótesis adoptadas|Принятые гипотезы|Ipotesi adottate|採用した仮定
Ce qui n'est pas modélisé|What is not modelled|未建模内容|Was nicht modelliert ist|Qué no se modeliza|Что не моделируется|Cosa non è modellato|モデルに含まれない要素
Ce qui invalide cette conception|What invalidates this design|使设计失效的条件|Was diesen Entwurf ungültig macht|Qué invalida este diseño|Что делает проект непригодным|Cosa invalida questo progetto|この設計を無効にする条件
Le point électrique|Electrical considerations|电气事项|Elektrische Aspekte|Aspectos eléctricos|Электрические аспекты|Aspetti elettrici|電気的条件
TENU|HELD|满足|ERFÜLLT|CUMPLIDO|ВЫДЕРЖАНО|RISPETTATO|成立
SERRÉ|TIGHT|裕量有限|KNAPP|AJUSTADO|ОГРАНИЧЕННЫЙ ЗАПАС|RIDOTTO|余裕限定
NON TENU|NOT HELD|不满足|NICHT ERFÜLLT|NO CUMPLIDO|НЕ ВЫДЕРЖАНО|NON RISPETTATO|不成立
NON ÉVALUABLE|NOT EVALUABLE|无法评估|NICHT BEWERTBAR|NO EVALUABLE|НЕ ПОДДАЁТСЯ ОЦЕНКЕ|NON VALUTABILE|評価不可
Valeurs typiques, sans garantie au pire cas|Typical values, no worst-case guarantee|典型值，无最坏情况保证|Typische Werte, keine Worst-Case-Garantie|Valores típicos, sin garantía de peor caso|Типовые значения, без гарантии худшего случая|Valori tipici, senza garanzia nel caso peggiore|代表値、最悪条件の保証なし
Dispersion du seuil du contact|Contact threshold spread|触点阈值离散|Kontakt-Schwellwertstreuung|Dispersión del umbral del contacto|Разброс порога контакта|Dispersione della soglia del contatto|接点しきい値のばらつき
Dispersion de l'aimant|Magnet spread|磁体离散|Magnetstreuung|Dispersión del imán|Разброс магнита|Dispersione del magnete|磁石のばらつき
Tolérance de montage non déclarée|Assembly tolerance unspecified|未声明装配公差|Montagetoleranz nicht angegeben|Tolerancia de montaje no declarada|Допуск сборки не указан|Tolleranza di montaggio non dichiarata|組立公差未入力
Plage de température non déclarée|Temperature range unspecified|未声明温度范围|Temperaturbereich nicht angegeben|Rango térmico no declarado|Диапазон температур не указан|Intervallo termico non dichiarato|温度範囲未入力
Température des mesures publiée : inconnue|Published measurement temperature: unknown|公布测量温度：未知|Temperatur der veröffentlichten Messungen: unbekannt|Temperatura de medición publicada: desconocida|Температура опубликованных измерений: неизвестна|Temperatura delle misure pubblicate: sconosciuta|公開測定値の温度：不明
Dérive de l'aimant en température|Magnet temperature drift|磁体温漂|Temperaturdrift des Magneten|Deriva térmica del imán|Температурный дрейф магнита|Deriva termica del magnete|磁石の温度ドリフト
Dérive du seuil du contact en température|Contact threshold temperature drift|触点阈值温漂|Temperaturdrift der Kontaktschwelle|Deriva térmica del umbral del contacto|Температурный дрейф порога контакта|Deriva termica della soglia del contatto|接点しきい値の温度ドリフト
Vieillissement de l'aimant|Magnet aging|磁体老化|Magnetalterung|Envejecimiento del imán|Старение магнита|Invecchiamento del magnete|磁石の経年変化
Perméabilité du matériau|Material permeability|材料磁导率|Materialpermeabilität|Permeabilidad del material|Проницаемость материала|Permeabilità del materiale|材料の透磁率
Défaut d'alignement|Misalignment|不对中|Fehlausrichtung|Desalineación|Несоосность|Disallineamento|位置ずれ
Rebond du contact|Contact bounce|触点弹跳|Kontaktprellen|Rebote del contacto|Дребезг контакта|Rimbalzo del contatto|接点バウンス
Cadence de commutation|Switching rate|开关频率|Schaltfrequenz|Frecuencia de conmutación|Частота переключения|Frequenza di commutazione|開閉頻度
Chocs et vibrations|Shock and vibration|冲击和振动|Stöße und Vibrationen|Choques y vibraciones|Удары и вибрации|Urti e vibrazioni|衝撃と振動
Pièces ferromagnétiques voisines|Nearby ferromagnetic parts|附近铁磁部件|Benachbarte ferromagnetische Teile|Piezas ferromagnéticas cercanas|Близкие ферромагнитные детали|Parti ferromagnetiche vicine|周辺の強磁性部品
Fermeture : entrefer maximal avant écart négatif|Closure: maximum gap before negative margin|闭合：裕量为负前的最大间隙|Schließen: maximaler Abstand vor negativer Reserve|Cierre: separación máxima antes de margen negativo|Замыкание: максимальный зазор до отрицательного запаса|Chiusura: traferro massimo prima di margine negativo|閉成：余裕が負になる前の最大ギャップ
Ouverture : entrefer minimal avant écart négatif|Opening: minimum gap before negative margin|断开：裕量为负前的最小间隙|Öffnen: minimaler Abstand vor negativer Reserve|Apertura: separación mínima antes de margen negativo|Размыкание: минимальный зазор до отрицательного запаса|Apertura: traferro minimo prima di margine negativo|開離：余裕が負になる前の最小ギャップ
Température : seuil de défaillance inconnu|Temperature: failure threshold unknown|温度：失效阈值未知|Temperatur: Ausfallschwelle unbekannt|Temperatura: umbral de fallo desconocido|Температура: порог отказа неизвестен|Temperatura: soglia di guasto sconosciuta|温度：故障しきい値不明
Ajout de matière ferromagnétique : nouvelle caractérisation|Added ferromagnetic material: recharacterise|添加铁磁材料：需重新表征|Ferromagnetisches Material hinzugefügt: neu charakterisieren|Material ferromagnético añadido: recaracterizar|Добавление ферромагнитного материала: новая проверка|Materiale ferromagnetico aggiunto: nuova caratterizzazione|強磁性材料の追加：再評価が必要
Changement d'aimant : nouvelle caractérisation|Magnet change: recharacterise|更换磁体：需重新表征|Magnetwechsel: neu charakterisieren|Cambio de imán: recaracterizar|Замена магнита: новая проверка|Cambio magnete: nuova caratterizzazione|磁石の変更：再評価が必要
Changement de classe : nouveau calcul|Class change: recalculate|更换等级：重新计算|Klassenwechsel: neu berechnen|Cambio de clase: recalcular|Изменение класса: новый расчёт|Cambio classe: ricalcolare|クラス変更：再計算が必要
Version du moteur|Engine version|引擎版本|Engine-Version|Versión del motor|Версия движка|Versione del motore|計算エンジン版
Versions des registres|Registry versions|登记表版本|Registerversionen|Versiones de registros|Версии реестров|Versioni dei registri|レジストリ版
Déclarations utilisateur|User declarations|用户声明|Benutzerangaben|Declaraciones del usuario|Заявления пользователя|Dichiarazioni utente|ユーザー入力
Entrefer fermé|Closed gap|闭合间隙|Geschlossener Abstand|Separación cerrada|Зазор в закрытом положении|Traferro chiuso|閉位置のギャップ
Entrefer ouvert|Open gap|断开间隙|Offener Abstand|Separación abierta|Зазор в открытом положении|Traferro aperto|開位置のギャップ
Tolérance de montage|Assembly tolerance|装配公差|Montagetoleranz|Tolerancia de montaje|Допуск сборки|Tolleranza di montaggio|組立公差
Température minimale|Minimum temperature|最低温度|Mindesttemperatur|Temperatura mínima|Минимальная температура|Temperatura minima|最低温度
Température maximale|Maximum temperature|最高温度|Höchsttemperatur|Temperatura máxima|Максимальная температура|Temperatura massima|最高温度
Perte admise au vieillissement|Allowed aging loss|允许老化损失|Zulässiger Alterungsverlust|Pérdida admitida por envejecimiento|Допустимая потеря при старении|Perdita ammessa per invecchiamento|許容経年損失
Fermeture typique|Typical closure|典型闭合|Typisches Schließen|Cierre típico|Типовое замыкание|Chiusura tipica|代表閉成距離
Ouverture typique|Typical opening|典型断开|Typisches Öffnen|Apertura típica|Типовое размыкание|Apertura tipica|代表開離距離
Prédiction physique|Physical prediction|物理预测|Physikalische Vorhersage|Predicción física|Физический прогноз|Previsione fisica|物理予測
Pire cas garanti|Guaranteed worst case|保证最坏情况|Garantierter ungünstigster Fall|Peor caso garantizado|Гарантированный худший случай|Caso peggiore garantito|最悪条件の保証
À caractériser|To be characterised|待表征|Zu charakterisieren|Por caracterizar|Требует характеристики|Da caratterizzare|特性評価が必要
Limites électriques|Electrical limits|电气限值|Elektrische Grenzen|Límites eléctricos|Электрические пределы|Limiti elettrici|電気的制限
Référence assemblée à confirmer|Assembled part number to confirm|待确认总成型号|Montierte Artikelnummer bestätigen|Referencia ensamblada por confirmar|Уточнить обозначение изделия в сборе|Codice assemblato da confermare|組立品番の確認が必要
Contrainte jointe|Combined constraint|联合约束|Gemeinsame Begrenzung|Restricción conjunta|Совместное ограничение|Vincolo congiunto|組合せ制約
Les maxima de tension, courant et puissance ne sont pas simultanés. Continu, efficace ou crête et charge à préciser. Aucun dimensionnement électrique validé.|Voltage, current and power maxima are not simultaneous. Specify DC, RMS or peak and load. No electrical sizing is validated.|电压、电流和功率最大值不可同时使用。需明确直流、有效值或峰值及负载。未验证电气选型。|Maxima von Spannung, Strom und Leistung gelten nicht gleichzeitig. Gleich-, Effektiv- oder Spitzenwert und Last angeben. Keine elektrische Auslegung bestätigt.|Los máximos de tensión, corriente y potencia no son simultáneos. Precise continua, eficaz o pico y carga. No se valida el dimensionamiento eléctrico.|Максимумы напряжения, тока и мощности не одновременны. Уточните DC, RMS или пик и нагрузку. Электрический расчёт не подтверждён.|I massimi di tensione, corrente e potenza non sono simultanei. Precisare continua, efficace o picco e carico. Nessun dimensionamento elettrico validato.|電圧・電流・電力の最大値は同時適用できません。直流・実効値・ピークと負荷を指定してください。電気設計は未検証です。
Revue R&D|R&D review|研发评审|F&E-Prüfung|Revisión I+D|Проверка НИОКР|Revisione R&S|研究開発レビュー
Contre-signature réservée à une revue publiée par la R&D sur cette révision.|Countersignature requires a published R&D review of this revision.|会签需要研发部门发布本修订版的评审。|Gegenzeichnung erfordert eine veröffentlichte F&E-Prüfung dieser Revision.|La contrafirma requiere una revisión I+D publicada de esta versión.|Контрподпись требует опубликованной проверки НИОКР этой версии.|La controfirma richiede una revisione R&S pubblicata di questa versione.|副署には、この版に対する公開済み研究開発レビューが必要です。
Donnée manquante|Missing data|缺失数据|Fehlende Daten|Dato faltante|Недостающие данные|Dato mancante|不足データ
Calibration : REFUSÉE|Calibration: REFUSED|标定：拒绝|Kalibrierung: ABGELEHNT|Calibración: RECHAZADA|Калибровка: ОТКЛОНЕНА|Calibrazione: RIFIUTATA|校正：拒否
Motif :|Reason:|原因：|Grund:|Motivo:|Причина:|Motivo:|理由：
Hypothèses à examiner : définition des approches ; datum/centre magnétique ; géométrie active de l'aimant.|Check approach definitions, datum/magnetic centre and active magnet geometry.|检查接近定义、基准/磁中心及磁体有效几何。|Ansatzdefinitionen, Bezug/Magnetzentrum und aktive Magnetgeometrie prüfen.|Revise definiciones de aproximación, referencia/centro magnético y geometría activa.|Проверьте определения подходов, базу/магнитный центр и активную геометрию.|Verificare definizioni di approccio, riferimento/centro magnetico e geometria attiva.|接近定義、基準・磁気中心、有効磁石形状を確認してください。
Calibration : ACCEPTÉE sur les données fournies|Calibration: ACCEPTED on supplied data|标定：基于所提供数据接受|Kalibrierung: anhand gelieferter Daten AKZEPTIERT|Calibración: ACEPTADA con datos suministrados|Калибровка: ПРИНЯТА по предоставленным данным|Calibrazione: ACCETTATA sui dati forniti|校正：提供データに対して合格
Centre ajusté (mm) :|Fitted centre (mm):|拟合中心 (mm)：|Angepasstes Zentrum (mm):|Centro ajustado (mm):|Подогнанный центр (мм):|Centro adattato (mm):|推定中心 (mm)：
Empreinte des sources :|Source fingerprint:|来源指纹：|Quellenfingerabdruck:|Huella de fuentes:|Отпечаток источников:|Impronta delle fonti:|出典フィンガープリント：
Empreinte cohérente. Cela ne constitue pas une contre-signature.|Fingerprint matches. This is not a countersignature.|指纹一致。这不构成会签。|Fingerabdruck stimmt. Dies ist keine Gegenzeichnung.|Huella coherente. Esto no constituye una contrafirma.|Отпечаток совпадает. Это не контрподпись.|Impronta coerente. Non costituisce una controfirma.|フィンガープリント一致。副署を意味しません。
Empreinte invalide ou format incompatible.|Invalid fingerprint or incompatible format.|指纹无效或格式不兼容。|Ungültiger Fingerabdruck oder inkompatibles Format.|Huella inválida o formato incompatible.|Неверный отпечаток или несовместимый формат.|Impronta non valida o formato incompatibile.|フィンガープリント無効、または形式非対応。
A · Géométrie active de M02|A · Active geometry of M02|A · M02 有效几何|A · Aktive Geometrie von M02|A · Geometría activa de M02|A · Активная геометрия M02|A · Geometria attiva di M02|A · M02の有効形状
B · Poses exactes D1 et D3|B · Exact D1 and D3 poses|B · D1/D3 精确姿态|B · Exakte Posen D1 und D3|B · Posiciones exactas D1 y D3|B · Точные позиции D1 и D3|B · Pose esatte D1 e D3|B · D1・D3の正確な配置
C · Point de référence magnétique|C · Magnetic reference point|C · 磁参考点|C · Magnetischer Bezugspunkt|C · Punto de referencia magnético|C · Магнитная опорная точка|C · Punto di riferimento magnetico|C · 磁気基準点
D · Mesures indépendantes|D · Independent measurements|D · 独立测量|D · Unabhängige Messungen|D · Mediciones independientes|D · Независимые измерения|D · Misure indipendenti|D · 独立測定
E · Rémanence et dispersion|E · Remanence and spread|E · 剩磁与离散|E · Remanenz und Streuung|E · Remanencia y dispersión|E · Остаточная индукция и разброс|E · Rimanenza e dispersione|E · 残留磁束密度とばらつき
F · Dispersion des contacts|F · Contact spread|F · 触点离散|F · Kontaktstreuung|F · Dispersión de contactos|F · Разброс контактов|F · Dispersione dei contatti|F · 接点のばらつき
G · Dérives en température|G · Temperature drifts|G · 温漂|G · Temperaturdriften|G · Derivas térmicas|G · Температурные дрейфы|G · Derive termiche|G · 温度ドリフト
H · Tolérances d'assemblage|H · Assembly tolerances|H · 装配公差|H · Montagetoleranzen|H · Tolerancias de montaje|H · Допуски сборки|H · Tolleranze di montaggio|H · 組立公差
I · Pièces ferromagnétiques|I · Ferromagnetic parts|I · 铁磁部件|I · Ferromagnetische Teile|I · Piezas ferromagnéticas|I · Ферромагнитные детали|I · Parti ferromagnetiche|I · 強磁性部品
J · Vieillissement|J · Aging|J · 老化|J · Alterung|J · Envejecimiento|J · Старение|J · Invecchiamento|J · 経年変化
K · Dynamique et vibrations|K · Dynamics and vibration|K · 动态与振动|K · Dynamik und Vibrationen|K · Dinámica y vibraciones|K · Динамика и вибрации|K · Dinamica e vibrazioni|K · 動特性と振動
L · Limites électriques assemblées|L · Assembled electrical limits|L · 总成电气限值|L · Elektrische Grenzen der Baugruppe|L · Límites eléctricos ensamblados|L · Электрические пределы сборки|L · Limiti elettrici dell'assieme|L · 組立品の電気的制限
M · Câbles et environnement|M · Cables and environment|M · 电缆与环境|M · Kabel und Umgebung|M · Cables y entorno|M · Кабели и среда|M · Cavi e ambiente|M · ケーブルと環境
N · Autres familles du catalogue|N · Other catalog families|N · 目录中的其他系列|N · Weitere Katalogfamilien|N · Otras familias del catálogo|N · Другие семейства каталога|N · Altre famiglie del catalogo|N · カタログ内の他系列
O · Critères de validation R&D|O · R&D acceptance criteria|O · 研发验收标准|O · F&E-Abnahmekriterien|O · Criterios de validación I+D|O · Критерии приёмки НИОКР|O · Criteri di validazione R&S|O · 研究開発の合格基準`;
const extras = `
Revue R&D publiée|Published R&D review|已发布研发评审|Veröffentlichte F&E-Prüfung|Revisión I+D publicada|Опубликованная проверка НИОКР|Revisione R&S pubblicata|公開済み研究開発レビュー
Contre-signature serveur non activée|Server countersignature not enabled|服务器会签未启用|Server-Gegenzeichnung nicht aktiviert|Contrafirma del servidor no activada|Контрподпись сервера не активирована|Controfirma server non attivata|サーバー副署は未有効化
Une revue publiée atteste la revue de cette révision, pas une certification du produit.|A published review attests review of this revision, not product certification.|已发布评审证明对本版本进行了评审，不构成产品认证。|Eine veröffentlichte Prüfung bestätigt die Prüfung dieser Revision, keine Produktzertifizierung.|Una revisión publicada acredita la revisión de esta versión, no una certificación del producto.|Опубликованная проверка подтверждает рассмотрение версии, а не сертификацию изделия.|Una revisione pubblicata attesta la verifica di questa versione, non una certificazione del prodotto.|公開レビューは当該版の審査を示すもので、製品認証ではありません。`;
const path = "src/lib/i18n/messages.json",
  dictionary = JSON.parse(readFileSync(path, "utf8"));
for (const row of (rows + extras).split("\n")) {
  const [key, ...translations] = row.split("|");
  if (translations.length !== 7 || translations.some((s) => !s))
    throw new Error("Translation width: " + key);
  dictionary[key!] = translations;
}
writeFileSync(path, JSON.stringify(dictionary, null, 2) + "\n");
