/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as StandexRouteImport } from './routes/standex'
import { Route as StandexIndexRouteImport } from './routes/standex.index'
import { Route as StandexConsoleRouteImport } from './routes/standex.console'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const StandexRoute = StandexRouteImport.update({
  id: '/standex',
  path: '/standex',
  getParentRoute: () => rootRouteImport,
} as any)
const StandexIndexRoute = StandexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandexRoute,
} as any)
const StandexConsoleRoute = StandexConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => StandexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/standex': typeof StandexRouteWithChildren
  '/standex/console': typeof StandexConsoleRoute
  '/standex/': typeof StandexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/standex/console': typeof StandexConsoleRoute
  '/standex': typeof StandexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/internal': typeof InternalRoute
  '/standex': typeof StandexRouteWithChildren
  '/standex/console': typeof StandexConsoleRoute
  '/standex/': typeof StandexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/internal'
    | '/standex'
    | '/standex/console'
    | '/standex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design' | '/internal' | '/standex/console' | '/standex'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/internal'
    | '/standex'
    | '/standex/console'
    | '/standex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  InternalRoute: typeof InternalRoute
  StandexRoute: typeof StandexRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standex': {
      id: '/standex'
      path: '/standex'
      fullPath: '/standex'
      preLoaderRoute: typeof StandexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standex/': {
      id: '/standex/'
      path: '/'
      fullPath: '/standex/'
      preLoaderRoute: typeof StandexIndexRouteImport
      parentRoute: typeof StandexRoute
    }
    '/standex/console': {
      id: '/standex/console'
      path: '/console'
      fullPath: '/standex/console'
      preLoaderRoute: typeof StandexConsoleRouteImport
      parentRoute: typeof StandexRoute
    }
  }
}

interface StandexRouteChildren {
  StandexConsoleRoute: typeof StandexConsoleRoute
  StandexIndexRoute: typeof StandexIndexRoute
}

const StandexRouteChildren: StandexRouteChildren = {
  StandexConsoleRoute: StandexConsoleRoute,
  StandexIndexRoute: StandexIndexRoute,
}

const StandexRouteWithChildren =
  StandexRoute._addFileChildren(StandexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  InternalRoute: InternalRoute,
  StandexRoute: StandexRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
