/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as StandexRouteImport } from './routes/standex'
import { Route as ApiLeadVerifyUploadRouteImport } from './routes/api/lead/verify-upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const StandexRoute = StandexRouteImport.update({
  id: '/standex',
  path: '/standex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadVerifyUploadRoute = ApiLeadVerifyUploadRouteImport.update({
  id: '/api/lead/verify-upload',
  path: '/api/lead/verify-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/standex': typeof StandexRoute
  '/api/lead/verify-upload': typeof ApiLeadVerifyUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/standex': typeof StandexRoute
  '/api/lead/verify-upload': typeof ApiLeadVerifyUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/standex': typeof StandexRoute
  '/api/lead/verify-upload': typeof ApiLeadVerifyUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design' | '/standex' | '/api/lead/verify-upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design' | '/standex' | '/api/lead/verify-upload'
  id: '__root__' | '/' | '/design' | '/standex' | '/api/lead/verify-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  StandexRoute: typeof StandexRoute
  ApiLeadVerifyUploadRoute: typeof ApiLeadVerifyUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standex': {
      id: '/standex'
      path: '/standex'
      fullPath: '/standex'
      preLoaderRoute: typeof StandexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead/verify-upload': {
      id: '/api/lead/verify-upload'
      path: '/api/lead/verify-upload'
      fullPath: '/api/lead/verify-upload'
      preLoaderRoute: typeof ApiLeadVerifyUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  StandexRoute: StandexRoute,
  ApiLeadVerifyUploadRoute: ApiLeadVerifyUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
